services:
  z2m-ember-multiprotocol:
    container_name: z2m-ember-multiprotocol
    image: "m33ts4k0z/z2m-ember-multiprotocol:latest"
    volumes:
      - .env:/.env
    # - your_zigbee2mqtt_data_directory:/opt/zigbee2mqtt/data # Change the left portion of the colon to your zigbee2mqtt data directory
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0